### ISSUE TITLE
Duck Eggs grant the "Take Aim" advancement.

### ISSUE THREAD

**Issue by noolaan** [team-abnormals/environmental#120]
Throwing a duck egg at an entity will grant you the "Take Aim" advancement. This is a vanilla advancement meant for arrows, not eggs.

**Comment by bageldotjpg** [comment]
I can not reproduce this, could you provide a video?

**Comment by bageldotjpg** [comment]
This shouldn't occur unless something is adding duck egg entities to the `#minecraft:arrows` entity tag
