### ISSUE TITLE
woodcutter and kiln mod support

### ISSUE THREAD

**Issue by Hypsellis** [team-abnormals/environmental#126]
I link there a list I made for charm woodcutter and kiln for supporting properly other mods. I think it will help you as well.
https://github.com/svenhjol/Covalent/issues/6

**Comment by bageldotjpg** [comment]
Currently only plan to support Abnormals, Quark, and Farmer's Delight recipes on our ends as anymore will get very hard to keep track of and follow and I don't tend to play with many other mods other than those. Your best luck is getting support in those mods or creating a datapack, I don't have the time to maintain tons of recipes for various mods

**Comment by Hypsellis** [comment]
Eh I understand you, it's never easy to maintain compability for every mods. I can do this maintenance if you're fine with it and don't wish to do it yourself.

**Comment by Hypsellis** [comment]
It would be at least nice to add the missing vanilla recipes (stone slab, smooth stone slab, smooth sandstone slab and stair, smooth red sandstone slab and stair, smooth quartz slab and stair).

**Comment by MarioSMB** [comment]
Generally speaking it is contributors who play with both mods that are most likely to submit and maintain compatibility recipes, the developers don't necessarily need to focus on third party support (a broken recipe or two is not going to crash the game regardless).
As someone who has personally submitted updates to Environmental compatibility in other mods, I cannot respect the approach taken here, as it shuts down potential contributors and ensures poor support between your mod(s) and others.  

I hope the developers will reconsider allowing people to provide support for their favourite mods, the cross-compatibility in today's modding scene has been a luxury many are becoming accustomed to.
