### ISSUE TITLE
Vertical slabs uses the wrong tag

### ISSUE THREAD

**Issue by LeoBeliik** [team-abnormals/environmental#131]
Enviromental's vertical slabs uses quark:vertical_slab**s** while quark uses quark:vertical_slab as tags

Environmental-1.16.5-1.0.0
Quark-r2.4-308
Forge 36.0.40

![2021-03-02_00 03 55](https://user-images.githubusercontent.com/11804768/109590477-d0dccf80-7aea-11eb-89b4-d2deb8e8cad9.png)
![2021-03-02_00 03 58](https://user-images.githubusercontent.com/11804768/109590483-d20dfc80-7aea-11eb-98c1-3837b58a1e4f.png)

**Comment by bageldotjpg** [comment]
I believe quarks now use the proper naming scheme so this can be closed
