### ISSUE TITLE
[Suggestion] Adjustable spawn weights for certain features

### ISSUE THREAD

**Issue by SirChamomile** [team-abnormals/environmental#137]
I would love to have a toggle for a flower forest adjacent biome for the wisteria trees that would be similar to the regular flower forest, resulting in a small concentration of the wisteria, but it might be easier to simply expose the weight of the delphinium and the wisteria so we could tweak how often they spawn. I would be very happy if the trees were much sparser or at least less evenly distributed as they are now.

**Comment by bageldotjpg** [comment]
Re-directing to #240
