### ISSUE TITLE
startup error

### ISSUE THREAD

**Issue by DODO2227vvb** [team-abnormals/environmental#142]
![123](https://user-images.githubusercontent.com/80121589/110153030-aea9c100-7e0c-11eb-8e74-6b45265f0f84.PNG)
Environmental (environmental) encountered an error during the load_registries event phase
Javalang IllegalficcessError: tried to access method net. minecraft. world. gen. treedecorator.TreeDecoratorType.(init>(Lcom/mojang/serialization/Codec;)V from class

**Comment by bageldotjpg** [comment]
Provide a latest.log if possible

**Comment by bageldotjpg** [comment]
Closed due to inactivity
