### ISSUE TITLE
Natural bamboo acts weird in Blossom biomes

### ISSUE THREAD

**Issue by noap123** [team-abnormals/environmental#146]
The bamboo in the blossom biomes break when it spawns
![2021-03-07_14 38 07](https://user-images.githubusercontent.com/72410346/110241867-7365da00-7f53-11eb-9ac6-914431b4ec5e.png)

**Comment by bageldotjpg** [comment]
Environmental doesn't change how bamboo works, your game seems to be broken or this is caused by another mod
