### ISSUE TITLE
[Suggestion] More sawmill recipes

### ISSUE THREAD

**Issue by Azmalent** [team-abnormals/environmental#147]
Sawmills could use some more recipes:
- Stripping logs and wood
- Recycling doors, trapdoors, signs, Quark chests, fences, pressure plates and buttons
- Crafting Quark posts from logs

**Comment by MarioSMB** [comment]
Let me just say, it's almost ludicrous that Mojang didn't add this when including all the other stations (especially the stone cutter)...  

Also, support for woods from more of the popular mods would be great (BoP, BYG and BetterEndForge come to mind).  
I've been slowly working on those three myself in a separate repository just so we can make more use of the sawmill on my server: https://github.com/MarioSMB/datapacks/tree/main/sawmill_recipes

**Comment by Brun333rp** [comment]
I have a question: can any mod support Environmental's recipes, or they need to require Abnormals Core as a dependency to support these recipes?

**Comment by MarioSMB** [comment]
Any mod can indeed support Environmental's sawmill, as it's just recipes in the data pack portion of the mod.

**Comment by Brun333rp** [comment]
that's good to know. thanks!
