### ISSUE TITLE
Baby villager that are spawned in environmental biomes isnt registered with proper clothing

### ISSUE THREAD

**Issue by kihgy** [team-abnormals/environmental#151]
Go to blossom forest, ice spikes or forest, flower foresy biome and spawn in a baby villager, the baby will take the default skin.

**Comment by warning-djkajslh** [comment]
Haven't tested with nitwit yet as they don't spawn naturally

**Comment by bageldotjpg** [comment]
Can not reproduce.
If you are using /summon, that happens with vanilla villagers too
