### ISSUE TITLE
Kiln smelts only 4 items when using 1 coal

### ISSUE THREAD

**Issue by DeadPigman17** [team-abnormals/environmental#152]
Instead of the normal 8, when you use a coal on a kiln it only smelts 4 items. I don't know if the same thing happens with other kinds of fuel.

**Comment by DeadPigman17** [comment]
Just found out that it's an incompatibility with Polymorph, and it also happens with Charm's kiln.

**Comment by FynnWaelsing** [comment]
Can confirm that this is an incompatibility with Polymorph. Removing Polymorph restores the normal function of the kiln.

Environmental 1.16.5 - 1.0.0
Abnormals Core 1.16.5 - 3.1.1
polymorph-forge-1.16.5-0.24.jar

**Comment by bageldotjpg** [comment]
This is being tracked on the Polymorph github and seems to occur with other mods so please track it there
