### ISSUE TITLE
Conflict with StepUp mod

### ISSUE THREAD

**Issue by faeldray** [team-abnormals/environmental#160]
This mod removes the ability to walk up one block height without jumping, which is added by [StepUp](https://www.curseforge.com/minecraft/mc-mods/stepup).

I tested it just with Abnormals Core 1.16.5-3.1.1, Environmental 1.16.5-1.0.0, and StepUp 1.16.4-0.2.0

I imagine that this is related to Issue #73

**Comment by RHSD** [comment]
I have the same issue

**Comment by Xetaxheb** [comment]
This can probably be closed as it should be fixed by #218 / cb3a700
