### ISSUE TITLE
Twig Nests cause massive frame drops when removing and inputting items.

### ISSUE THREAD

**Issue by dmsw0303** [team-abnormals/environmental#165]
The frame drops you get from adding and removing a single item happen quickly enough that it's actually hard to notice the frame drops, but if you completely fill one with some eggs and then try removing all of them semi-quickly, the game will drop hundreds of frames. This also works vice versa.

Java 15, in case that ends up mattering.

**Comment by bageldotjpg** [comment]
Can not reproduce
Reopen if this occurs only with environmental installed on the latest forge version, and provide a log
