### ISSUE TITLE
Outdated/incomplete/broken documentation

### ISSUE THREAD

**Issue by TheRealWormbo** [team-abnormals/environmental#166]
Both the Github and Curseforge pages for this mod reference a page on the Minecraft Abnormals Wiki, which seems very outdated and incomplete. Links on that page go to generic item/mobs/effects/biomes pages that mostly don't distinguish between the individual Abnormals mods and/or don't include Environmental-specific information.

**Comment by bageldotjpg** [comment]
Yeah, the wiki is very broken, we're aware and we are exploring better options of documentation
