### ISSUE TITLE
Cherry Tree Carpets don't break when the bottom block breaks

### ISSUE THREAD

**Issue by DereC4** [team-abnormals/environmental#172]
Unlike normal carpet type blocks these kinda just float when you break the block below them. I was wondering if they could have behavior like a normal carpet where when the block below the carpet is displaced the carpet breaks so that you can clear land in Blossom biomes easier.

**Comment by bageldotjpg** [comment]
This is intended, because it matches the behavior of Quark's leaf carpets. If you think it should be changed, report it to them
