### ISSUE TITLE
[1.16.5] Clucking ducks and quadruplet eggs

### ISSUE THREAD

**Issue by MarioSMB** [team-abnormals/environmental#176]
The ducks from this mod are clucking like chickens! Also, upon throwing a duck egg, it appeared as if one baby popped out, then 3 other ducklings separated from it...

**Comment by bageldotjpg** [comment]
Clucking - kinda intended, we didn't have sound files for them yet - they'll be available in the next update
Quadruplet eggs - a vanilla feature that can happen very rarely with chicken eggs as well!
