### ISSUE TITLE
Koi "Serenity" Effect prevents wandering trader spawns

### ISSUE THREAD

**Issue by DereC4** [team-abnormals/environmental#178]
The effect you get from having a koi around seems to prevent wandering traders from randomly spawning too.

**Comment by JacksonPlayz** [comment]
Serenity prevents entities classified as `MONSTER` from spawning. Try adding the wandering trader to the tag `serenity_whitelist` to see if it changes anything. Don't see any reason why it would stop wandering traders though.

**Comment by bageldotjpg** [comment]
Certain this is a case of unluck, because Wandering Traders are not considered monsters
