### ISSUE TITLE
Crash with Lord of the Rings mod

### ISSUE THREAD

**Issue by bigbull646** [team-abnormals/environmental#180]
While updating my modpack I tried installing LotR mod however it crashed while loading the game, and the crashes stopped once I disabled Environmental. According to the Mod team was something to do with Environmental. Here is a copy of my crash report from my modpack. I just wanted to share it in case it could be fixed in the future.

[crash-2021-04-07_22.01.58-client.txt](https://github.com/team-abnormals/environmental/files/6280092/crash-2021-04-07_22.01.58-client.txt)

And another crash report with just Environmental and LotR mod installed

[crash-2021-04-08_09.48.11-client.txt](https://github.com/team-abnormals/environmental/files/6280218/crash-2021-04-08_09.48.11-client.txt)

**Comment by WenXin20** [comment]
Hello, I've also gotten this crash. I'm using Forge v36.1.4, Environmental v1.0, and LotR v3.0.
Mod Link: https://www.curseforge.com/minecraft/mc-mods/the-lord-of-the-rings-mod-renewed
[Crash Report](https://gist.github.com/WenXin20/bba2485b91d287c63dac683276e4a6ba)

**Comment by bageldotjpg** [comment]
Unfortunately nothing we can do.
The crash report is not very telling of anything and the mod is closed source.
