### ISSUE TITLE
Kiln recipes are not faster

### ISSUE THREAD

**Issue by hotdog95** [team-abnormals/environmental#183]
While JEI and the JSON recipes state that the recipe only takes 5 seconds / 100 ticks, this is not the case. The processing time is still 10 seconds / 200 ticks yet the fuel consumption is halfed (1 coal will only cook 4 items)

I have only tested the stone recipe (cobble to stone)

Mod version: 1.16.5-1.0.0

**Comment by bageldotjpg** [comment]
This is caused by Polymorph
