### ISSUE TITLE
Weird FPS drop

### ISSUE THREAD

**Issue by thedeerirty** [team-abnormals/environmental#184]
![2021-04-11_13 43 49](https://user-images.githubusercontent.com/58305182/114315266-32ba2d00-9acc-11eb-9097-77ecf6aff4c9.png)
![2021-04-11_13 44 16](https://user-images.githubusercontent.com/58305182/114315268-33eb5a00-9acc-11eb-82a4-c59317fae998.png)
![2021-04-11_13 44 23](https://user-images.githubusercontent.com/58305182/114315269-351c8700-9acc-11eb-8b2e-9b635abe8a5c.png)

I do admit this could be chalked up to a lot of different things, I do, I'm just checking off my list so to say of what might be causing it
But for some reason, staring or looking at particular parts of Cherry Leaves cause a substantial fps drop, but only in survival mode?
Switching to spectator or creative has it disappear.

**Comment by thedeerirty** [comment]
It seems to be any situation where a leaf is above another leave? or a few above another.

**Comment by thedeerirty** [comment]
Also seems with and without shaders

**Comment by Ozzuneoj** [comment]
If you are using optifine try turning off anisotropic filtering. It is used to sharpen and clarify mipmapped textures when viewed at sharp angles. I had some serious performance problems with anisotropic filtering when looking at a huge forest of BOP autumn trees recently. I'm not sure what causes it... likely just the sheer number of angled mipmapped surfaces a forest creates, but it can apparently make Minecraft bring a 3060 Ti to it's knees at 1080P, so I don't think everything is working as intended.

Please report back if that fixes it for you. It's worth a shot. :)

**Comment by thedeerirty** [comment]
It did not fix it; i never had it on to begin with it seems.

**Comment by Ozzuneoj** [comment]
It may also be worth it to check to see if you have anisotropic filtering applied in your nvidia drivers. Either as a global setting or specifically for Minecraft (it may be listed as javaw.exe).
