### ISSUE TITLE
Why is there nothing on the mod on the mod page ?

### ISSUE THREAD

**Issue by Krampus69** [team-abnormals/environmental#185]
Hi,
I'm trying to understand this mod. But the front page doesn't say anything about it.
There is no images page.
Even the link to its official website is broken.

How much thousands of downloads this mod missed just because of this nonexisting com ? What is this mod ? Give us some info dammit

**Comment by bageldotjpg** [comment]
We currently do not have any form of documentation, but we are looking into options.
Please be patient while we do this.
You can ask any questions or search for info at our discord, https://discord.com/invite/abnormals
