### ISSUE TITLE
[1.16.5] Items not cooking quicker in the Kiln

### ISSUE THREAD

**Issue by MarioSMB** [team-abnormals/environmental#186]
Everything is taking the same amount of time (10 seconds) to cook in the Kiln as in a furnace. The JEI tooltip states that it should take 5 seconds.

**Comment by MarioSMB** [comment]
This applies to all the Kiln recipes currently, by the looks of it.

**Comment by MarioSMB** [comment]
Just an update, I tried fixing this by adjusting the cooking time in a data pack, JEI now says 2 seconds and it's *still* taking 10 seconds. My guess is, the Kiln is currently hardcoded to use furnace cooking times for some reason.

**Comment by bageldotjpg** [comment]
Nope, this is an issue caused by performant
