### ISSUE TITLE
Enviromental breaks other mods step assist

### ISSUE THREAD

**Issue by clmitchell-159** [team-abnormals/environmental#188]
**Issue**
The step assist added by Mekanism, Mana & Artifice (and several other mods) does not work when Environmental is installed.

**Related Info**
The step assist from Yak Pants does work.

**Reproduce**
_Mekanism:_
1. Install Environmental (and Abnormals Core) & Mekanism.
2. Equip a charged Free Runners.
3. Try to run on top of block without jumping.

_Mana & Artifice:_
1. Install Environmental (and Abnormals Core) and Mana & Artifice (and dependencies).
2. Equip a Staff of the Pilgrim in your off hand.
3. Try to run on top of block without jumping.

**Related Issues**
This is probably related to #73 and #160

**Comment by naufalejaz** [comment]
Tested this on 0.5.2.

Had the same issue with none of the step assists working. Running shoes was working.
Removed Environmental from my single player world and all of them started working again. 

Same hypothesis from removing it from my server.

**Comment by Xetaxheb** [comment]
This can probably be closed as it should be fixed by #218 / cb3a700

**Comment by judicius** [comment]
why close it before the fix is live?
