### ISSUE TITLE
Compatibility with Fast Leaf Decay

### ISSUE THREAD

**Issue by chimericdream** [team-abnormals/environmental#189]
I saw this mentioned in the Discord, but couldn't find any issues here for it. I noticed that leaves from Wisteria trees don't decay quickly with the [Fast Leaf Decay](https://www.curseforge.com/minecraft/mc-mods/fast-leaf-decay) mod. Looking at the code for both mods and similar issues reported in the FLD GitHub, it looks like the reason is because `WisteriaLeavesBlock` inherits directly from `Block` instead of `LeavesBlock`. I'm not familiar enough with Forge's API or the Environmental codebase to know if there is a specific reason for this, so I don't know if there would need to be a change in the FLD mod to explicitly support Wisteria leaves or if that's something that could be changed here.

**Comment by Olafski** [comment]
I just released an update to FastLeafDecay which also checks the `leaves` BlockTag. Environmental trees are now supported. :-)
