### ISSUE TITLE
Crash when harvesting rice in a debug world

### ISSUE THREAD

**Issue by 6-28318530717958** [team-abnormals/environmental#197]
When right-clicking on rice in a debug world as if harvesting it, the game crashes. 

To recreate: create a debug world and go to 111 70 643. click on the rice there.

Crash log: https://pastebin.com/CAtnqTBH

**Comment by bageldotjpg** [comment]
Rice has been removed in favor of Farmer's Delights rice as of 62ad492f64dde5df64224a8ac43519d462469241
