### ISSUE TITLE
You should be able to edit which biomes mobs spawn in, in the config files.

### ISSUE THREAD

**Issue by TheDinoguy** [team-abnormals/environmental#200]
I really think vanilla world gen is ugly and I like terraforged but certain mobs rely on vanilla biome spawn conditions (I'm looking at you Yak} in order to spawn in and Terraforged doesn't have vanilla mountain biomes. I feel like for the sake of easy access, we should be able to configure which mobs spawn in which biomes, like what Alex's mobs already does.

**Comment by bageldotjpg** [comment]
Re-directing to #240
