### ISSUE TITLE
Bread isn't duck food

### ISSUE THREAD

**Issue by Moralle** [team-abnormals/environmental#201]
Bread should be removed from the duck food tag, since it is actually bad for them. Yes, these are just virtual ducks that can't actually be harmed, but I still think it would be better to remove it, similarly to how Mojang decided to make parrots tamable with seeds instead of cookies. Here's a list of food in Minecraft that ducks can eat:
-Wheat
-Seeds
-(Water)Melon
-Sweet Berries

**Comment by bageldotjpg** [comment]
This is a bit of a misconception, bread isn't actually bad for ducks as long as its in moderation, and due to how breeding works in Minecraft it is in moderation.
Either way it's still changed as of d23cd7383b76336026698809c7d5745050474a31 as its a common misconception but its brought up a lot
