### ISSUE TITLE
potential issue involving YUNG's better strongholds/mineshafts

### ISSUE THREAD

**Issue by Armokthespideroverlord** [team-abnormals/environmental#202]
this might have already been addressed, but it's a possibility that the replacements structures that YUNG's better strongholds/mineshafts introduces might prevent the spawning of the healer pouch item this mod adds in. Of course I only tested this briefly by spawning a bunch of zombies in both dungeons, so it's possible that these mods don't have any incompatibility with this mod regarding the healer pouch

**Comment by BugmanBugman** [comment]
Seconding this for repurposed structures' mineshafts
