### ISSUE TITLE
Environmental village buildings out-compete vanilla buildings, making loot rare

### ISSUE THREAD

**Issue by TheDeviantCrafter** [team-abnormals/environmental#203]
Environmental adds multiple village buildings which can generate in place of vanilla buildings. They seem to have a high weight, causing them to replace at least half of all vanilla buildings. The result is that the rarer vanilla buildings like the tool forge, fletcher and cartographer are frustratingly rare.

I suggest two changes:

1. Significantly decrease the weight of the common Environmental buildings, such as the yellow terracotta houses in acacia villages. These are the worst offenders.
2. Add a config to allow pack devs to tweak the frequency of villages. A global multiplier for all Environmental village buildings would probably be enough. Lowering this value would decrease the weight of all Environmental village buildings by a percentage.

**Comment by Freshah** [comment]
(not a fix, just a suggestion) If you use Repurposed Structures, you can use their compat datapacks to repopulate the villages better,
