### ISSUE TITLE
Kiln smelting is 2x more expensive instead of being 2x faster.

### ISSUE THREAD

**Issue by zabodan** [team-abnormals/environmental#206]
https://github.com/team-abnormals/environmental/blob/ed46ed12c4a9159f18f69cd170dfe7e14f1d041b/src/main/java/com/minecraftabnormals/environmental/common/tile/KilnTileEntity.java#L23

**Comment by bageldotjpg** [comment]
It is two times faster and functions properly. If this is not working for you, check if you have polymorph installed. It seems to break when installed alongside Polymorph,
