### ISSUE TITLE
Modded villagers not taking jobs

### ISSUE THREAD

**Issue by StrangerSon71** [team-abnormals/environmental#220]
Modded villagers(including from ice and fire, so might not be your fault) don't take modded workstations.
Modlist:
abnormals_core-1.16.5-3.1.1.jar
antiqueatlas-5.4.4-forge.jar
bgcore-1.16.5-3.2.jar
CavesAndCliffsBackport-1.16.5-5.2.jar
Enhanced-Mushrooms-1.16.5-3.0.8.jar
abnormals_delight-1.16.5-1.1.1.jar
Abundance-1.16.5-1.0.5.jar
AI-Improvements-1.16.2-0.3.0.jar
alexsmobs-1.11.0.jar
allurement-1.16.5-1.2.0.jar
appleskin-forge-mc1.16.x-2.0.0.jar
archers_paradox-1.16.4-1.2.0.jar
Artifacts-1.16.5-2.9.3.jar
atmospheric-1.16.5-3.1.0.jar
AutoRegLib-1.6-49.jar
autumnity-1.16.5-2.1.1.jar
Bayou-Blues-1.16.5-1.0.5.jar
berry_good-1.16.5-4.1.1.jar
Better-Badlands-1.16.5-2.0.3.jar
buzzier_bees-1.16.5-3.0.1.jar
caelus-forge-1.16.5-2.1.3.0.jar
citadel-1.7.1-1.16.5.jar
cofh_core-1.16.4-1.2.1.jar
comforts-forge-1.16.5-4.0.1.1.jar
Controlling-7.0.0.23.jar
cookielicious-1.16.5-1.2.2.jar
tombstone-1.16-6.4.5.jar
CraftTweaker-1.16.5-7.1.0.316.jar
create-mc1.16.5_v0.3.1c.jar
curioofundying-forge-1.16.5-5.2.0.0.jar
curios-forge-1.16.5-4.0.5.2.jar
curiouselytra-forge-1.16.5-4.0.2.3.jar
DarkerDepths-1.16.5-1.0.1.jar
dusk-1.4.jar
environmental-1.16.5-1.0.0.jar
expandability-2.0.1-forge.jar
extraboats-1.16.5-2.1.0.jar
FarmersDelight-1.16.5-0.4.5.jar
FastLeafDecay-v25.jar
FastFurnace-1.16.4-4.4.0.jar
FastWorkbench-1.16.4-4.5.1.jar
ferritecore-2.0.4-forge.jar
Fruitful-1.16.5-2.1.0.jar
geckolib-forge-1.16.5-3.0.41.jar
Germinate V.1.1.jar
iceandfire-2.1.8-1.16.5.jar
infernal-expansion-forge-1.3.jar
JEITweaker-1.16.5-1.0.1.31.jar
Jellyfishing-1.6.9.jar
jei-1.16.5-7.7.0.106.jar
mgui-1.16.5-3.2.0.jar
minecolonies-0.14.237-ALPHA-universal.jar
MoreJellyfish-1.1.5.jar
mowziesmobs-1.5.19.jar
mystical_pumpkins-0.3.0.jar
neapolitan-1.16.5-2.1.0.jar
Orcinus-Caves-1.0.0.jar
oreganized-1.16.4-0.5.0-beta.jar
Peculiars-1.16.4-1.1.0.jar
personality-1.16.5-1.0.2.jar
Placebo-1.16.4-4.5.0.jar
Quark-r2.4-313.jar
QuarkOddities-1.16.3.jar
rats-7.2.0-1.16.5.jar
repurposed_structures-1.16.5-2.7.5-forge.jar
sapience-1.16.4-1.1.1.jar
savageandravage-1.16.5-3.1.0.jar
cobbler-1.6.1.jar
shutupexperimentalsettings-1.0.3.jar
sodium-forge-2.3.jar
structurize-0.13.195-ALPHA-universal.jar
tetra-1.16.5-3.12.0.jar
tetranomicon-1.3.jar
endergetic-1.16.4-3.0.0.jar
theoneprobe-1.16-3.1.4.jar
OuterEnd-0.2.13.jar
Toast-Control-1.16.4-4.3.1.jar
upgrade_aquatic-1.16.5-3.1.0.jar
dungeonsarise1.16.5-1.2.72a.jar
YungsApi-1.16.4-Forge-6.jar
BetterCaves-Forge-1.16.4-1.1.2.jar
BetterMineshafts-Forge-1.16.4-2.0.4.jar
BetterStrongholds-1.16.4-1.1.jar
YungsExtras-Forge-1.16.4-1.0.jar

**Comment by bageldotjpg** [comment]
Works fine with just environmental so it must be another mod causing it

**Comment by StrangerSon71** [comment]
Should I do this post to every mod author on the list? Do you know who I should try next? This is a major bug with no certain cause.

**Comment by bageldotjpg** [comment]
No, best method is a binary search. Remove half of the mods and see if the problem persists. If not, try the other half. Keep removing half until you narrow down what the cause is
