### ISSUE TITLE
Wandering boots blocks walked messed up

### ISSUE THREAD

**Issue by krohs** [team-abnormals/environmental#221]
If I walk 2.4 blocks the boots add 9 blocks to the counter, and if I sneak while walking it adds 27

**Comment by krohs** [comment]
And by 2.4 blocks I mean between 2 blocks like this [https://imgur.com/a/9lRpYkW](url)

**Comment by bageldotjpg** [comment]
Fixed in dd29c128099d77ac633b73ab262ca02c00412ffb
