### ISSUE TITLE
Panic buff is a curse when current health is over 10 hearts.

### ISSUE THREAD

**Issue by ArmageddonX430** [team-abnormals/environmental#224]
Playing a modpack with Spice of Life: Carrot Edition, Environmental, and Corail Tombstone.  I generally have 20 hearths of health, and when I get hit, the "Blessing" enchant from Corail Tombstone will grant a random buff.  When blessing grants "Panic!" I get stuck in place without the ability to move.

Preferably the healer's pouch "Panic!" ability should grant a speed boost based on % health missing from full, rather than # of hearts less than 10.

**Comment by bageldotjpg** [comment]
Already fixed indev
