### ISSUE TITLE
The Hood discord issue

### ISSUE THREAD

**Issue by blacksythe** [team-abnormals/environmental#236]
Add discord integration support so the thief hood does not show ??? In discord. This is purely for ease of chat moderation. While its possible to get username from logs. Not all staff have access and staff cant be on the server all the time.

**Comment by bageldotjpg** [comment]
The username-obscuring functionality of the Thief's Hood has been removed as of the latest update, we are not happy with it and do not think it belongs

**Comment by Darkmega18** [comment]
> 
> 
> The username-obscuring functionality of the Thief's Hood has been removed as of the latest update, we are not happy with it and do not think it belongs

Nooooooooo. :(
