### ISSUE TITLE
Can't get a chest on slabfish

### ISSUE THREAD

**Issue by Tutueti** [team-abnormals/environmental#239]
Hello,

I'm not being able of getting a backpack on a slabfish, no matter what I do. I tried right-clicking it with a chest from all angles possible.
Is there something I'm missing about this?

I'm playing singleplayer with the following mods on 1.16.5, forge 36.2.0:

abnormals_core-1.16.5-3.2.0.jar
blame-1.16.5-3.4.1-forge.jar
byg-1.3.1.jar
cameraoverhaul-1.0-1.16.4.jar
champions-forge-1.16.5-2.0.1.7.jar
citadel-1.7.3-1.16.5.jar
collective-1.16.5-2.58.jar
corpsecomplex-forge-1.16.5-4.0.2.5.jar
CreativeCore_v2.2.1_mc1.16.5.jar
Desolation+1.1.0-1+1.16.5.jar
DungeonsArise-1.16.5-2.1.47-release.jar
DynamicSurroundings-1.16.4-4.0.4.2.jar
EnhancedVisuals_v1.3.32_mc1.16.5.jar
EnigmaticGraves-1.6.1.jar
environmental-1.16.5-1.1.0.jar
EpicFightMod-1.16.5-4.1.6.jar
FallingTree-1.16.5-2.11.5.jar
healingcampfire_1.16.5-3.3.jar
iceandfire-2.1.8-1.16.5.jar
jei-1.16.5-7.7.1.118.jar
journeymap-1.16.5-5.7.3.jar
JustEnoughResources-1.16.3-0.12.0.100.jar
mowziesmobs-1.5.19.jar
performant-1.16.2-5-3.72m.jar
projectvibrantjourneys-1.16.5-3.2.8.jar
ShoulderSurfing-1.16.5-2.2.1.jar
skin_changer-0.2.2.jar
SpartanShields-1.16.5-2.1.2.jar
SpartanWeaponry-1.16.4-2.1.0-beta-4.jar
TerraForged-1.16.5-0.2.14.jar
Waystones_1.16.5-7.6.2.jar
wizardstaff-1.16.5-1.7.0.jar
[BETA]dannys_expansion1.16.5-1.0.9.1.jar

**Comment by bageldotjpg** [comment]
The slabfish has to be tamed first, using tropical fish
