### ISSUE TITLE
Crash Environmental Events

### ISSUE THREAD

**Issue by thepriz** [team-abnormals/environmental#245]
When I enter a certain area in my world I get a crash that could be in Environmental. I have included the crash log
[crash-2021-09-28_09.21.01-server.txt](https://github.com/team-abnormals/environmental/files/7245972/crash-2021-09-28_09.21.01-server.txt)
.

**Comment by bageldotjpg** [comment]
1.16 is not supported anymore, but looks an Apotheosis issue
