### ISSUE TITLE
Setting fizzy yogurt (from the copper pots mod) to slabfish_snack tag in environmental and then feeding a slabfish a fizzy yogurt to a slabfish crashes the game

### ISSUE THREAD

**Issue by thelegitdolt** [team-abnormals/environmental#254]
Wanted to post this here in case this was some crazy incompatibility issue, since I have tried with foxes and no crash occured.

https://cdn.discordapp.com/attachments/905649496455782411/907525976613851168/crash-2021-11-08_22.58.43-client.txt - crash report

https://cdn.discordapp.com/attachments/905649496455782411/907525934561775616/latest.log - latest.log

**Comment by bageldotjpg** [comment]
do not attach files, use paste site

**Comment by thelegitdolt** [comment]
https://pastebin.com/qVby7FRV crash report
log is too big for me to paste

**Comment by bageldotjpg** [comment]
copper pot issue, needs to check if its a player entity before casting
