### ISSUE TITLE
[Suggestion] Increase seed drop rate on cattail

### ISSUE THREAD

**Issue by BozoJim** [team-abnormals/environmental#256]
I discovered that cattail can be used to create string and was hoping to set up a string farm as an alternative to farming spiders.
In that process, it turns out tall cattail only has a 50% drop rate, and the regular cattail has 25% meaning it's not sustainable. The drop rate of seeds needs to be a bit more than 1-1 to make it a sustainable string farm.

**Comment by bageldotjpg** [comment]
grow cattails on underwater farmland for it to actually grow the cattail seeds
