### ISSUE TITLE
[Feature Request] Ducks should drop feathers.

### ISSUE THREAD

**Issue by Reshy** [team-abnormals/environmental#263]
Ducks really should drop feathers like chickens do when killed, or should interact with mods that cause them to drop them when struck (v-tweaks I believe).  As is, the duck is kind of just a chicken-shaped pig, as it has no secondary resource you can get from it.

**Comment by bageldotjpg** [comment]
Ducks do drop feathers when killed.
https://github.com/team-abnormals/environmental/blob/main/src/main/resources/data/environmental/loot_tables/entities/duck.json
