### ISSUE TITLE
[Suggestion] Allow Creatures to stay spawned outside of their biome if moved.

### ISSUE THREAD

**Issue by silicon11** [team-abnormals/environmental#269]
I was thinking you could allow/keep creatures outside of their biome, you could keep them spawned if maybe you used a nametag or something? I wanted to create a koi pond outside of their biome but when I moved them away with another mod and them came back to the area they despawned.

**Comment by bageldotjpg** [comment]
Koi do not despawn if they have a custom name or are picked up and placed using a bucket
