### ISSUE TITLE
Cherry Tree Leaves not appearing as pink but green?

### ISSUE THREAD

**Issue by geexed** [team-abnormals/environmental#282]
https://www.reddit.com/r/BetterMinecraftForge/comments/v2mlos/cherry_tree_leaf_color_from_environmental_mod_not/

My cherry tree leaves are supposed to be pink but instead they are appearing as green.  The Cherry Leaf carpet block is pink but the Cherry Tree Leaves in the actual trees are not.  Read my reddit post to get a better understanding and a visual of what I'm talking about.  If you know how to resolve this issue or have a fix, please let me know.  Thanks!

**Comment by bageldotjpg** [comment]
Frequent issue with optifine and resource packs, nothing we can really do
