### ISSUE TITLE
Growing trees overwrite blocks too zealously

### ISSUE THREAD

**Issue by moonfather1** [team-abnormals/environmental#284]
A wisteria tree grew from a sapling that i planted next to my tree chopping contraption from "create mod".  One log replaced a windmill bearing. I also lost two windmill sails nearby.

expected behavior:
Blocks other than leaves (by tag) and "replaceable" blocks (method on block class) should not be destroyed. There can be more exceptions (plant parts mostly) but killing a windmill bearing is a no-no.

**Comment by Punkin-GH** [comment]
what version of minecraft did this happen on, and what version of the mod were you using?

**Comment by moonfather1** [comment]
mc was 1.16.5, not sure about your mod, i no longer have that hard drive.

**Comment by bageldotjpg** [comment]
Should be fixed as of 1.18 or 1.19
