### ISSUE TITLE
When I try run github version 1.18.x in normal Minecraft Launcher, it crashes.

### ISSUE THREAD

**Issue by TeiBri** [team-abnormals/environmental#285]
The same problem has Upgrade Aquatic 1.18.x too with mixin.json.... I dont know, how to fix it.

There it is
[debug.log](https://github.com/team-abnormals/environmental/files/9283003/debug.log)
.
[latest.log](https://github.com/team-abnormals/environmental/files/9283005/latest.log)

**Comment by bageldotjpg** [comment]
We do not offer support with compiled versions. They are not released for a reason.
