### ISSUE TITLE
Cattails are seeded in water but not on land

### ISSUE THREAD

**Issue by DevotedMedic** [team-abnormals/environmental#292]
![2023-02-03_17 24 53](https://user-images.githubusercontent.com/80219680/216670354-bdc6e2b5-49cd-49ec-8776-84f136843f6b.png)
![2023-02-03_17 25 17](https://user-images.githubusercontent.com/80219680/216670396-71721627-7c05-4f36-a0df-788010818233.png)
![2023-02-03_17 25 25](https://user-images.githubusercontent.com/80219680/216670444-19736367-e55d-4427-83c3-86395fd9c66a.png)
Found a few patches to demonstrate this; when generated, only the cattails in the water have their seeds ready to harvest unlike the ones on land. I assume none of them are supposed to have their seeds ready to harvest when generating

**Comment by DevotedMedic** [comment]
Additionally the cattails in the water do not have an animation when the seeds are ready to harvest

**Comment by bageldotjpg** [comment]
Intentional new change, to show they grow the seeds when in water.
