### ISSUE TITLE
crashing when creating a new world (1.19.2)

### ISSUE THREAD

**Issue by ClephLeSDF** [team-abnormals/environmental#301]
[crash-2023-02-06_00.53.33-client.txt](https://github.com/team-abnormals/environmental/files/10614161/crash-2023-02-06_00.53.33-client.txt)

**Comment by FrogBirdd** [comment]
Was having the same issue, turns out it's a problem with Clayworks. There's a recipe in it for the Kiln that uses the now removed Mud Bricks, disabling that recipe via datapack fixed the crash

**Comment by bageldotjpg** [comment]
Fixed on Clayworks end
