### ISSUE TITLE
Bees related issues in blossom forests

### ISSUE THREAD

**Issue by thelegitdolt** [team-abnormals/environmental#304]
I looked at 10 unique blossom forests, and did /locate poi #minecraft:bee_home.

Out of the 10 forests, I was only able to find 3 beehives. 2 of which was on a cherry tree, 1 of which was on a birch tree. This is a lot rarer than in vanilla forests. Imo you should like, increase the spawn rate and stuff

https://www.youtube.com/watch?v=EvrR-bxBh8Y&ab_channel=DoltHHaven video

**Comment by thelegitdolt** [comment]
In addition to that, the hives on cherry trees I was able to find was usually located in the middle of the trunk, which looks kinda weird. Instead, they should be attached to the bottom side of the branches.

<img width="1512" alt="Screen Shot 2023-02-05 at 7 54 20 PM" src="https://user-images.githubusercontent.com/50085439/216881110-f314106c-c40d-4a7c-b9cf-83460ef1cd72.png">

**Comment by bageldotjpg** [comment]
![image](https://user-images.githubusercontent.com/55970498/216882607-2375d289-4d49-4e5c-9d2b-facd8bccc326.png)
Like Forests and Birch Forests, Cherry Trees have a 0.2% chance of having a beehive. This is intentional
In addition, that is just how the beehive placer chooses to place beehives. It can be anywhere, but it tends to choose them that way.

**Comment by thelegitdolt** [comment]
cherry trees are a lot sparser than these forests though. even still i think it's bad that i saw 3 beehives generating in 10 different forests

**Comment by thelegitdolt** [comment]
https://www.youtube.com/watch?v=aJGXJCy-R34&ab_channel=DoltHHaven the video i was talking about. figured i'd post this here

**Comment by thelegitdolt** [comment]
Went back and took some screenshots. 
<img width="1512" alt="Screen Shot 2023-04-20 at 12 06 00" src="https://user-images.githubusercontent.com/50085439/233463835-b1d5b38a-a3ff-40e8-a9c6-a4b16d445c96.png">
<img width="1512" alt="Screen Shot 2023-04-20 at 12 06 07" src="https://user-images.githubusercontent.com/50085439/233463836-3e101f38-0c2e-4b7c-83a7-f03203e9152a.png">

<img width="1512" alt="Screen Shot 2023-04-20 at 12 06 11" src="https://user-images.githubusercontent.com/50085439/233463839-04324d15-4ecf-4954-a93e-790cc9b3d693.png">

In a typical forest biome chunk, there are usually about anywhere from 4-6 trees. However, as cherry trees are much larger than normal trees, only 1-2 trees usually spawn per chunk.  

<img width="1512" alt="Screen Shot 2023-04-20 at 12 06 57" src="https://user-images.githubusercontent.com/50085439/233463993-9782e009-a44c-4abc-9c95-b6710beac46f.png">
<img width="1512" alt="Screen Shot 2023-04-20 at 12 07 08" src="https://user-images.githubusercontent.com/50085439/233464007-9d72e2fe-f710-4b17-bfd3-f7a4a571c741.png">
<img width="1512" alt="Screen Shot 2023-04-20 at 12 07 01" src="https://user-images.githubusercontent.com/50085439/233464019-ab0476ab-c8f9-44af-bc80-ee5e5a6df781.png">

Unless the intention is to make bees much rarer in blossom forests than in normal forests, the spawn rate of bees on trees should be increased to reflect this.
