### ISSUE TITLE
Issues with Swamp Ground Cover

### ISSUE THREAD

**Issue by thelegitdolt** [team-abnormals/environmental#308]
<img width="1512" alt="Screen Shot 2023-02-05 at 9 37 44 PM" src="https://user-images.githubusercontent.com/50085439/216892081-fe26e744-0820-4e98-809a-b55d659a0f19.png">

Swamps ground covers are a lot sparser than they were on the 1.16 version. Features like sugarcane, small flowers, duckweed, cattails, and huge mushrooms, seem to be a lot rarer.

**Comment by bageldotjpg** [comment]
![image](https://user-images.githubusercontent.com/55970498/216894253-4033e024-8ff3-4f33-a340-2ef9890c6600.png)
Looks fine to me. We don't touch the sugar cane and small flowers. Happy with the rate of mushrooms, duckweed, and cattails.

**Comment by thelegitdolt** [comment]
yea ur right, m' bad, was used to playing with UA lol

**Comment by thelegitdolt** [comment]
actually, just booted up 1.16.5 to check,  duckweed was a lot more common in that version
