### ISSUE TITLE
Koi spawn extremely frequently

### ISSUE THREAD

**Issue by WitheredWasabi** [team-abnormals/environmental#311]
Issue is carried over from 1.16. It's likely that there's no mob cap for koi, or that there's just no other aquatic animal taking it up, as it takes some time for them to accumulate. 
![2023-02-05_23 54 55](https://user-images.githubusercontent.com/38932715/216915594-ff2d6e58-fa13-4ac0-ab09-049f4c48ecf4.png)

**Comment by bageldotjpg** [comment]
intentional, just out of place cuz they dont have a lot of variants, but their waters are meant to be pretty full of koi
