### ISSUE TITLE
Environmental biomes showing up too often in 1.18.2

### ISSUE THREAD

**Issue by Lozf** [team-abnormals/environmental#321]
This mod is awesome, just to start with.  It seems to be weighting environmental biomes pretty high,  I use biomes o plenty and byg, and even with those in the mix, there's always an environmental biome in every three biomes (usually the environmental woods).  I'd love to be able to turn them down a bit.  The wisteria are so awesome!

**Comment by bageldotjpg** [comment]
The weight can be changed via datapack by editing the modded biome slice
