### ISSUE TITLE
Slabfish, Ducks, and Fish Do Not Spawn in Marshes 1.19.2

### ISSUE THREAD

**Issue by ChimIsTrash** [team-abnormals/environmental#332]
I'm on the latest version of Forge on 1.19.2, with Blueprint 6.1.1, Environmental 3.0.0, Neapolitan 4.0.2, and Atmospheric 5.0.0 without any other mods or datapacks installed.

Frogs appear to be the only mobs that spawn in marshes, with no other mobs spawning on land or in water. (Hostile mobs do spawn at night though.)

Mobs highlighted upon generation.
![image](https://user-images.githubusercontent.com/86890911/224451049-2cae0cd1-62d2-41cd-87b1-60d15bba1f27.png)

Mobs highlighted after 10 minutes.
![image](https://user-images.githubusercontent.com/86890911/224451063-9a41df17-5c81-4ad7-ab17-45c28a40e766.png)

However, they appear to spawn immediately upon generation in swamps and mangrove swamps.
![image](https://user-images.githubusercontent.com/86890911/224451975-468df32a-5abb-4fc8-884f-a7311411c613.png)
![image](https://user-images.githubusercontent.com/86890911/224452457-b542552c-480d-4250-bec6-a7e3417db7ef.png)

**Comment by thelegitdolt** [comment]
i think this is because marshes are not tagged as #minecraft:is_swamp

**Comment by bageldotjpg** [comment]
Fixed indev
