### ISSUE TITLE
NO WORKING ENVIROMENTAL SERVER&CLIENT

### ISSUE THREAD

**Issue by MrJorman** [team-abnormals/environmental#341]
![image](https://user-images.githubusercontent.com/55187962/226554388-30735600-802e-4c33-b4be-7e4563b7c7cd.png)

**Comment by MrJorman** [comment]
@bageldotjpg  you are either dumb or blind.

**Comment by MrJorman** [comment]
It's been a bug for like 2 weeks now, no one can run your fucking mod on the server. I have tried all versions

**Comment by MrJorman** [comment]
**Take a clean Forge and put it on a server (SERVER) and run Blueprints.jar and Enviromental.jar you will get a START ERROR!!**

**Comment by thelegitdolt** [comment]
based
