### ISSUE TITLE
[1.19.2] Game never loads/freezes with Jade and WTHIT

### ISSUE THREAD

**Issue by nataliat1026** [team-abnormals/environmental#343]
If _Jade_ or _WTHIT_ is installed, the game starts to load, never gets past a white screen, and stops responding entirely. It doesn't actually create a crash report, but the whole program freezes up and I manually have to end the task.

I went through and enabled mods one at a time to be sure the conflict is with _Environmental_ itself.

Tested with:

- _Jade_ versions 8.8.1 and 8.8.0
- _WTHIT_ version 5.14.1

Just wanted to report this since they're very popular mods.

Also wanted to note that it loads up fine with _The One Probe_ installed. That doesn't cause any issues.

Sorry about all the changes to the title. I got mixed up while testing this all out and just wanted to make sure I was being accurate with the issue report.

**Comment by bageldotjpg** [comment]
Since this is all one issue going to redirect this to #362
