### ISSUE TITLE
[1.19.2] Most adding biome modifier features are not tags

### ISSUE THREAD

**Issue by thelegitdolt** [team-abnormals/environmental#345]
Unlike most other abnormals mods, the biome modifiers adding most environmental features (all of them apart from mud disks and cattails) uses specific biome tags or biomes instead of the usual `#environmental:has_feature/feature_name`.

**Comment by bageldotjpg** [comment]
We use tags when needed, it doesn't matter is the modifiers are data driven and replaceable anyway
