### ISSUE TITLE
Various Cattail Weirdness

### ISSUE THREAD

**Issue by thelegitdolt** [team-abnormals/environmental#350]
1. When water is taken away from a waterlogged cattail, the `fake_waterlogged` state does not become set to false and therefore the cattail will keep playing its animated texture 

2. When water is added to the bottom part of a waterlogged cattail, only the bottom part of it will become `fake_waterlogged`

https://cdn.discordapp.com/attachments/729307658602938389/1096996990182764554/Screen_Recording_2023-04-15_at_20.11.00.mov

**Comment by bageldotjpg** [comment]
Fixed through the Cattail rework in the next update
