### ISSUE TITLE
Game never loads when environmental is installed on some computers with unknown reasons

### ISSUE THREAD

**Issue by BurningSulphur** [team-abnormals/environmental#351]
We discussed this crash on discord a few weeks ago. I thought I had reported it but I realized I must have forgotten to click the submit button. 

This is the crash log from my game : https://mclo.gs/ik1vAt3
Crash log of MildlyMiffed#6394 https://mclo.gs/Tt6nIqs
Crash log of rose_#7017 https://mclo.gs/xlDn3aC

Since the discussion on the discord, I have published the mod pack 
I was working on, If you want to try and recreate it yourself, try and add environmental to it:
https://www.curseforge.com/minecraft/modpacks/bumblemancy

**Comment by wtchappell** [comment]
I'm pretty sure I'm hitting this as well with a modpack I'm working on. Just a solid hang a little after `Dispatching Module Step CONSTRUCT_CLIENT` shows up in the logs.

**Comment by Zenithrium** [comment]
Same thing seems to be happening to my friends but not me with the same set of mods. Ceases shortly after ```Dispatching Module Step CONSTRUCT_CLIENT```
Log: 
[environmentalhanglog.log](https://github.com/team-abnormals/environmental/files/11862716/environmentalhanglog.log)

**Comment by bageldotjpg** [comment]
Since this is all one issue going to redirect this to #362
