### ISSUE TITLE
MC 1.19.2 hangs on startup with Environmental and FTB Chunks together 

### ISSUE THREAD

**Issue by SuperStormer** [team-abnormals/environmental#354]
I'm using MC 1.19.2 with Forge 1.19.2 and these mods:
```
architectury-6.5.77-forge.jar
blueprint-1.19.2-6.1.2.jar
environmental-1.19.2-3.0.0.jar
ftb-chunks-forge-1902.3.21-build.266.jar
ftb-library-forge-1902.3.18-build.208.jar
ftb-teams-forge-1902.2.13-build.100.jar
````

When I try to launch the instance, Minecraft hangs (for over 7 minutes before I killed it) with a white screen. 

Log file:
https://gnomebot.dev/paste/1099784425794977905

**Comment by bageldotjpg** [comment]
Since this is all one issue going to redirect this to #362
