### ISSUE TITLE
Biomes of new villager variants is hardcoded

### ISSUE THREAD

**Issue by thelegitdolt** [team-abnormals/environmental#357]
https://github.com/team-abnormals/environmental/blob/1.19.x/src/main/java/com/teamabnormals/environmental/core/registry/EnvironmentalVillagers.java

Currently making a mod that would allow Env's villager types to spawn in some other modded biomes. However, The villagers are registered in such ways that it is impossible for any outside code to refer to them at all. 

It would be nice if the new villager types are declared, and also that the biomes they spawn in become tag-driven to make things easier.

**Comment by thelegitdolt** [comment]
Oh wait there's a by biome method never mind but you should still make them tag driven plz

**Comment by thelegitdolt** [comment]
would still be nice to declare them too so you don't have to pull a this every time
<img width="605" alt="Screen Shot 2023-05-02 at 17 02 49" src="https://user-images.githubusercontent.com/50085439/235810173-fbbcdef2-84e3-4ac8-b3af-9c61989a4a63.png">

**Comment by bageldotjpg** [comment]
They're initialized before tags, we can not make them tag driven or else there will be a start up crash. Villager types are really finicky.
