### ISSUE TITLE
Conflicts with create mod. 1.18.2

### ISSUE THREAD

**Issue by Redfalcon58** [team-abnormals/environmental#361]
When I load both crate and the environmental mod together there seems to be some sort of conflict that doesn't allow them to load the game up. The game will constantly load not even bringing up the mojang screen followed by not responding. I get an exit code -805306369 with the message "This may be resolved by allocating additional memory in the configuration of Minecraft: Java edition." I have allocated 10 GB of ram to the game, but I don't know what else to do. I have tried changing the different versions of create and several other things.

**Comment by bageldotjpg** [comment]
Since this is all one issue going to redirect this to #362
