### ISSUE TITLE
version 1.19.2 seems to be incompatible with OptiFine

### ISSUE THREAD

**Issue by Samson107gh** [team-abnormals/environmental#370]
The game wont load to the main menu, it doesn't even get to the Mojang loading screen, it just shows the window and never loads, I tried everything I can think of and nothing seems to work apart from removing OptiFine. I know 1.18.2 works with OptiFine but not 1.19.2

**Comment by bageldotjpg** [comment]
Unfortunately can't support issues with Optifine as it is closed source and near impossible to bug fix with.
