### ISSUE TITLE
Podzol Paths Cannot Be Tilled With A Hoe

### ISSUE THREAD

**Issue by peepeepoopoocaca** [team-abnormals/environmental#374]
Podzol paths do not reflect the normal behavior of path blocks in vanilla in relation to their ability to be turned into farmland.

Podzol in vanilla can be turned into path blocks, and then these path blocks can be turned into farmland using a hoe.

The Minecraft wiki states: "A podzol block can be turned into a dirt path by pressing use on it with any type of shovel, but it cannot be tilled with a hoe to make farmland. However, the player can first use the shovel on the podzol to turn it into dirt path, then use the hoe on the dirt path to turn it into farmland."

It is unclear whether podzol path blocks have had this behavior intentionally changed.

This change may cause difficulty when turning moss into dirt, which is a common form of making dirt renewable in the game. Allowing podzol paths to be turned into farmland is heavily recommended to allow this feature to continue existing.

**Comment by bageldotjpg** [comment]
Podzol paths can't be tilled because Podzol can't be tilled
Though I'm not sure how this prevents turning moss into dirt - Podzol drops dirt when broken and that can be tilled?
