### ISSUE TITLE
Thatch Stairs use incorrect Block Models when Upside Down

### ISSUE THREAD

**Issue by josephgilbert** [team-abnormals/environmental#378]
As the title says.  When connecting thatch stairs upside down, it seems like the stair itself goes into another position than it should.  This happens with all thatch types in Environmental, but it does not occur with the beach grass thatch stairs from Upgrade Aquatic.

To reproduce this bug, take any of the thatch stairs from Environmental and place them on 2 adjacent walls upside down.  Then, connect the stairs via a stair in the corner.  The stair will have the incorrect model.  You can see this better in the picture below.  I am currently playing on 1.19.2.
![2023-09-30_19 36 32](https://github.com/team-abnormals/environmental/assets/42681167/d87dd09c-d47b-46dc-b7e0-3f3fe7afcb52)
![2023-09-30_19 36 43](https://github.com/team-abnormals/environmental/assets/42681167/c3ab568d-a3b2-4605-a12b-542268230cf9)

**Comment by bageldotjpg** [comment]
Fixed indev for the next update
