### ISSUE TITLE
New slabfishes (pine, spiny thicket, scrubland, aspen, kousa) do not have custom bucket textures and are missing translations

### ISSUE THREAD

**Issue by thelegitdolt** [team-abnormals/environmental#389]
<img width="655" alt="Screenshot 2023-11-26 at 14 14 23" src="https://github.com/team-abnormals/environmental/assets/50085439/a9604f25-c640-4d52-8818-afe3e94655bc">

**Comment by bageldotjpg** [comment]
Fixed indev
