### ISSUE TITLE
Pigs do not become muddy on top of Muddy Mangrove Roots

### ISSUE THREAD

**Issue by thelegitdolt** [team-abnormals/environmental#394]

**Comment by thelegitdolt** [comment]
<img width="1512" alt="Screenshot 2023-11-27 at 00 24 20" src="https://github.com/team-abnormals/environmental/assets/50085439/c7273a17-974b-472e-8ce6-d0b2eab4f4f8">

Not muddy

**Comment by bageldotjpg** [comment]
Non-issue - muddy mangrove roots don't have the lower hitbox that Mud does.
