### ISSUE TITLE
Truffle pie missing texture and localization 

### ISSUE THREAD

**Issue by evanbones** [team-abnormals/environmental#400]
Environmental 1.19.2 3.0.0

Small issue, but I figured I'd report it anyways. I could've sworn it had a name and texture in the 1.18.2 version
![image](https://github.com/team-abnormals/environmental/assets/74276616/9e21d321-79cf-46fe-aa8b-80b6c775e1c9)

Edit: It seems like truffle crates are now missing as well in the latest version

**Comment by bageldotjpg** [comment]
Truffle Pie & Crates were removed... what's this recipe from?

**Comment by evanbones** [comment]
Ah ha, I'm almost positive it's from Create Central Kitchen then. For some reason they registered the recipe again under the Environmental modid. Thanks!

**Comment by kitovoi111** [comment]
the same problem
