### ISSUE TITLE
The texture of  "Truffle Pie" was missing

### ISSUE THREAD

**Issue by MCER2020** [team-abnormals/environmental#422]
Problem : The texture of  "Truffle Pie" was missing. I can see it after i put down it on the ground. But the texture was missing when i have it on my hand.
Minecraft version : 1.19.2
Forge version : 43.4.0
Embeddium version : 0.3.18.1
Oculus version : 1.6.9
![texture](https://github.com/user-attachments/assets/9d8bd244-2cce-44f6-8871-44f271ddb1f9)

**Comment by bageldotjpg** [comment]
Truffle Pie was removed - this is an issue with a compatibility mod
