### ISSUE TITLE
Slabfish's inventories disappear when leaving it alone

### ISSUE THREAD

**Issue by Ryyye** [team-abnormals/environmental#75]
Don't know how to replicate this. Every now and then slabfish inventories just get wiped. On a server if that makes a difference.

**Comment by Ocelot5836** [comment]
More information is needed to figure out the issue. I'm leaving it open for now in case anyone else has the same issue and can give more information.

**Comment by bageldotjpg** [comment]
@Ocelot5836 We just figured out how to reproduce it, we all went to the Nether and left a Slabfish in the overworld and his items cleared when we returned.
