### ISSUE TITLE
Yak carpet is held too low

### ISSUE THREAD

**Issue by camcamcamcamcam** [team-abnormals/environmental#89]
Odd because carpet does not have this problem despite extending block/thin_block.json

I suspect the extra elements on the rug is causing this or thin_block "display": is being overridden somehow

![image](https://user-images.githubusercontent.com/21979237/98360402-9ad49500-208e-11eb-8c24-7bd666e972c5.png)
![image](https://user-images.githubusercontent.com/21979237/98360410-9f994900-208e-11eb-8a9b-a272ccc52fe5.png)
![image](https://user-images.githubusercontent.com/21979237/98360435-a9bb4780-208e-11eb-9d2f-9a3fe700b1cf.png)
![image](https://user-images.githubusercontent.com/21979237/98360441-ade76500-208e-11eb-9735-dacd5592b127.png)

**Comment by bageldotjpg** [comment]
fixed in dev
